compare_names = {
    "What's New": None,
    'Women': {'Tops': ['Jackets', 'Hoodies & Sweatshirts', 'Tees', 'Bras & Tanks'], 'Bottoms': ['Pants', 'Shorts']},
    'Men': {'Tops': ['Jackets', 'Hoodies & Sweatshirts', 'Tees', 'Tanks'], 'Bottoms': ['Pants', 'Shorts']},
    'Gear': {'Bags': None, 'Fitness Equipment': None, 'Watches': None},
    'Training': {'Video Download': None},
    'Sale': None}

compare_links = ['https://magento.softwaretestingboard.com/what-is-new.html',
                 'https://magento.softwaretestingboard.com/women.html',
                 'https://magento.softwaretestingboard.com/women/tops-women.html',
                 'https://magento.softwaretestingboard.com/women/tops-women/jackets-women.html',
                 'https://magento.softwaretestingboard.com/women/tops-women/hoodies-and-sweatshirts-women.html',
                 'https://magento.softwaretestingboard.com/women/tops-women/tees-women.html',
                 'https://magento.softwaretestingboard.com/women/tops-women/tanks-women.html',
                 'https://magento.softwaretestingboard.com/women/bottoms-women.html',
                 'https://magento.softwaretestingboard.com/women/bottoms-women/pants-women.html',
                 'https://magento.softwaretestingboard.com/women/bottoms-women/shorts-women.html',
                 'https://magento.softwaretestingboard.com/men.html',
                 'https://magento.softwaretestingboard.com/men/tops-men.html',
                 'https://magento.softwaretestingboard.com/men/tops-men/jackets-men.html',
                 'https://magento.softwaretestingboard.com/men/tops-men/hoodies-and-sweatshirts-men.html',
                 'https://magento.softwaretestingboard.com/men/tops-men/tees-men.html',
                 'https://magento.softwaretestingboard.com/men/tops-men/tanks-men.html',
                 'https://magento.softwaretestingboard.com/men/bottoms-men.html',
                 'https://magento.softwaretestingboard.com/men/bottoms-men/pants-men.html',
                 'https://magento.softwaretestingboard.com/men/bottoms-men/shorts-men.html',
                 'https://magento.softwaretestingboard.com/gear.html',
                 'https://magento.softwaretestingboard.com/gear/bags.html',
                 'https://magento.softwaretestingboard.com/gear/fitness-equipment.html',
                 'https://magento.softwaretestingboard.com/gear/watches.html',
                 'https://magento.softwaretestingboard.com/training.html',
                 'https://magento.softwaretestingboard.com/training/training-video.html',
                 'https://magento.softwaretestingboard.com/sale.html']