link_list = ['https://www.behance.net/for_you/onboarding?tracking_source=nav20', 'https://www.behance.net/galleries?tracking_source=nav20',
             'https://www.behance.net/hire?tracking_source=nav20', 'https://www.behance.net/assets?tracking_source=nav20',
             'https://www.behance.net/joblist?tracking_source=nav20', 'https://itunes.apple.com/us/app/behance/id489667151',
             'https://play.google.com/store/apps/details?id=com.behance.behance', 'https://www.behance.net/about',
             'https://www.behance.net/blog', 'http://www.adobe.com/legal/terms.html', 'http://www.adobe.com/privacy.html',
             'https://www.behance.net/misc/community', 'https://help.behance.net/', 'https://www.adobe.com/privacy/us-rights.html',
             'javascript:void(0)', 'javascript:void(0)', 'https://www.behance.net/', 'https://www.behance.net/for_you/onboarding?tracking_source=nav20',
             'https://www.behance.net/galleries?tracking_source=nav20', 'https://www.behance.net/hire?tracking_source=nav20',
             'https://www.behance.net/assets?tracking_source=nav20', 'https://www.behance.net/joblist?tracking_source=nav20',
             'https://www.behance.net/search/projects?tracking_source=typeahead_nav_suggestion_filter',
             'https://www.behance.net/search/images?tracking_source=typeahead_nav_suggestion_filter',
             'https://www.behance.net/search/users?tracking_source=typeahead_nav_suggestion_filter',
             'https://www.behance.net/search/assets?tracking_source=typeahead_nav_suggestion_filter',
             'https://www.behance.net/hire?tracking_source=typeahead_nav_suggestion_filter', 'https://www.behance.net/search/projects?tracking_source=nav20',
             'https://www.behance.net/search/projects?tracking_source=nav20', 'https://www.adobe.com/?promoid=RTQCN3LX', 'https://www.behance.net/agencydominion',
             'https://www.behance.net/agencydominion', 'https://www.behance.net/agencydominion', 'http://www.behance.net/', 'http://www.behance.net/',
             'https://www.behance.net/gallery/18988225/B-Yoga-Website/modules/128484259', 'https://www.behance.net/gallery/18988225/B-Yoga-Website/modules/128484255',
             'https://www.behance.net/gallery/18988225/B-Yoga-Website/modules/187555389', 'https://www.behance.net/gallery/18988225/B-Yoga-Website/modules/128484257',
             'https://www.behance.net/gallery/18988225/B-Yoga-Website/modules/128484261', 'https://www.behance.net/agencydominion', 'https://www.behance.net/agencydominion',
             'https://www.behance.net/galleries/ui-ux/web-design', 'https://www.behance.net/galleries/ui-ux/web-design',
             'https://www.behance.net/gallery/31799195/Fortnight-Lingerie?tracking_source=project_owner_other_projects',
             'https://www.behance.net/gallery/31799195/Fortnight-Lingerie',
             'https://www.behance.net/gallery/29713943/St-Regis-Monarch-Beach-Resort-Website?tracking_source=project_owner_other_projects',
             'https://www.behance.net/gallery/29713943/St-Regis-Monarch-Beach-Resort-Website', 'https://www.behance.net/agencydominion',
             'https://www.behance.net/gallery/32337441/Luma-Restaurant-Website?tracking_source=project_owner_other_projects',
             'https://www.behance.net/gallery/32337441/Luma-Restaurant-Website', 'https://www.behance.net/agencydominion',
             'https://www.behance.net/gallery/28659987/Drawing-Room-Restaurant-Website?tracking_source=project_owner_other_projects',
             'https://www.behance.net/gallery/28659987/Drawing-Room-Restaurant-Website', 'https://www.behance.net/agencydominion',
             'https://www.behance.net/armanhossainazad', 'https://www.behance.net/armanhossainazad', 'https://www.behance.net/agency_wolfe',
             'https://www.behance.net/agency_wolfe', 'https://www.behance.net/nikolastoxic', 'https://www.behance.net/nikolastoxic',
             'https://www.behance.net/johnkarwowski', 'https://www.behance.net/johnkarwowski', 'https://www.behance.net/Kheathrow', 'https://www.behance.net/Kheathrow', 'https://www.behance.net/kprsureshwebdesigner', 'https://www.behance.net/kprsureshwebdesigner', 'https://www.behance.net/andresladera', 'https://www.behance.net/andresladera', 'https://www.behance.net/webduck', 'https://www.behance.net/webduck', 'https://www.behance.net/MagicMode', 'https://www.behance.net/MagicMode', 'https://www.behance.net/wdasystems', 'https://www.behance.net/wdasystems', 'https://www.behance.net/agencydominion', 'https://www.behance.net/agencydominion', 'https://www.behance.net/search?content=users&country=CA&state=Ontario&city=Toronto', 'https://www.behance.net/whitmanemorson', 'https://www.behance.net/whitmanemorson', 'https://www.behance.net/johnspeed', 'https://www.behance.net/johnspeed', 'https://www.behance.net/agency-dominion', 'https://www.behance.net/agency-dominion', 'https://www.behance.net/search/projects?field=Art%20Direction', 'https://www.behance.net/search/projects?field=Web%20Design', 'https://www.behance.net/search/projects/Webdesign', 'https://www.behance.net/search/projects/Web', 'https://www.behance.net/search/projects/Website', 'https://www.behance.net/search/projects/wordpress', 'https://www.behance.net/search/projects/interactive', 'https://www.behance.net/search/projects/Responsive', 'https://www.behance.net/search/projects/Canada', 'http://creativecommons.org/licenses/by-nc/4.0/deed.ru_RU', 'https://www.behance.net/gallery/18988225/B-Yoga-Website?action=report', 'javascript:void(0)', 'https://www.behance.net/', 'https://www.behance.net/galleries', 'https://www.behance.net/updates/get-hired-on-behance', 'https://www.behance.net/updates/behance-assets', 'https://www.behance.net/updates/get-hired-on-behance-with-services', 'https://www.behance.net/joblist', 'https://www.behance.net/hire', 'https://www.behance.net/hire/graphic-designers', 'https://www.behance.net/hire/photographers', 'https://www.behance.net/hire/video-editors', 'https://www.behance.net/hire/web-designers', 'https://www.behance.net/hire/illustrators', 'https://www.behance.net/about', 'https://portfolio.adobe.com/', 'https://www.behance.net/blog', 'https://www.behance.net/careers', 'https://help.behance.net/', 'https://help.behance.net/hc/en-us/requests/new?ticket_form_id=4164', 'http://instagram.com/behance', 'http://twitter.com/behance', 'http://www.pinterest.com/behance', 'http://www.facebook.com/Behance', 'https://www.linkedin.com/company/151575', 'https://www.adobe.com/?promoid=RYGDMYVW', 'http://www.adobe.com/legal/terms.html', 'http://www.adobe.com/privacy.html', 'https://www.behance.net/misc/community', 'https://www.adobe.com/privacy/us-rights.html']

free_trial_links = ['https://adobe.com/express?promoId=SL4KM82F', 'https://www.adobe.com/creativecloud/plans.html?promoId=T32PLR49']

adobe_links = ['https://www.adobe.com/?promoid=TTGWL148', 'https://www.adobe.com/express/?geocheck=on&mv=other&promoid=8WLD4Y3J']

follow_links = ['https://www.behance.net/agencydominion', 'https://www.behance.net/agencydominion',
                'https://www.behance.net/agencydominion', 'https://www.behance.net/search?content=users&country=CA&state=Ontario&city=Toronto']

header_links = ['https://www.behance.net/for_you/onboarding?tracking_source=nav20', 'https://www.behance.net/galleries?tracking_source=nav20', 'https://www.behance.net/hire?tracking_source=nav20', 'https://www.behance.net/assets?tracking_source=nav20', 'https://www.behance.net/joblist?tracking_source=nav20']

footer_links = ['javascript:void(0)', 'https://www.behance.net/', 'https://www.behance.net/galleries', 'https://www.behance.net/updates/get-hired-on-behance', 'https://www.behance.net/updates/behance-assets', 'https://www.behance.net/updates/get-hired-on-behance-with-services', 'https://www.behance.net/joblist', 'https://www.behance.net/hire', 'https://www.behance.net/hire/graphic-designers', 'https://www.behance.net/hire/photographers', 'https://www.behance.net/hire/video-editors', 'https://www.behance.net/hire/web-designers', 'https://www.behance.net/hire/illustrators', 'https://www.behance.net/about', 'https://portfolio.adobe.com/', 'https://www.behance.net/blog', 'https://www.behance.net/careers', 'https://help.behance.net/', 'https://help.behance.net/hc/en-us/requests/new?ticket_form_id=4164', 'http://instagram.com/behance', 'http://twitter.com/behance', 'http://www.pinterest.com/behance', 'http://www.facebook.com/Behance', 'https://www.linkedin.com/company/151575', 'https://www.adobe.com/?promoid=RYGDMYVW', 'http://www.adobe.com/legal/terms.html', 'http://www.adobe.com/privacy.html', 'https://www.behance.net/misc/community', 'https://www.adobe.com/privacy/us-rights.html']
